[package]
name = "umi"
description = "UMI device management CLI tool"
license = "MPL-2.0"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
